# Generated by Django 5.1.7 on 2025-03-16 10:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('estadio', models.CharField(max_length=100)),
                ('fundacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2025)])),
                ('division', models.IntegerField(choices=[(1, 'Primera División')], default=1)),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('equipacion_principal', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios', regex='^[a-zA-ZáéíóúñÁÉÍÓÚÑ ]+$')])),
                ('equipacion_alternativa', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios', regex='^[a-zA-ZáéíóúñÁÉÍÓÚÑ ]+$')])),
                ('imagen_escudo', models.ImageField(blank=True, null=True, upload_to='escudos/')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('requisito', models.CharField(max_length=200)),
                ('efecto_quimica', models.IntegerField(default=0)),
                ('icono', models.CharField(max_length=100)),
                ('nivel', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField(validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(50)])),
                ('nacionalidad', models.CharField(max_length=50)),
                ('posicion', models.CharField(choices=[('POR', 'Portero'), ('DEF', 'Defensa'), ('MED', 'Mediocampista'), ('DEL', 'Delantero')], max_length=3)),
                ('valor_mercado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lesionado', models.BooleanField(default=False)),
                ('suspendido', models.BooleanField(default=False)),
                ('habilidad_ataque', models.IntegerField(default=50)),
                ('habilidad_defensa', models.IntegerField(default=50)),
                ('condicion_fisica', models.IntegerField(default=100)),
                ('es_extranjero', models.BooleanField(default=False)),
                ('dorsal', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='jugadores/')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='app_simulador.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Lesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('gravedad', models.CharField(choices=[('Leve', 'Leve'), ('Grave', 'Grave')], max_length=50)),
                ('tipo_lesion', models.CharField(choices=[('Muscular', 'Muscular'), ('Ósea', 'Ósea'), ('Articular', 'Articular'), ('Otra', 'Otra')], default='Muscular', max_length=50)),
                ('descripcion', models.TextField()),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_simulador.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('goles_local', models.IntegerField(default=0)),
                ('goles_visitante', models.IntegerField(default=0)),
                ('eventos', models.JSONField(default=dict)),
                ('jornada', models.IntegerField(default=1)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En juego', 'En juego'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=50)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='app_simulador.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='app_simulador.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinero', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha', models.DateField(auto_now_add=True)),
                ('completada', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('Compra', 'Compra'), ('Venta', 'Venta'), ('Préstamo', 'Préstamo')], default='Compra', max_length=50)),
                ('equipo_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_entrantes', to='app_simulador.equipo')),
                ('equipo_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_salientes', to='app_simulador.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_simulador.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('equipo_seleccionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_simulador.equipo')),
                ('logros_desbloqueados', models.ManyToManyField(blank=True, to='app_simulador.logro')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
