# Generated by Django 5.1.7 on 2025-03-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_simulador', '0003_equipo_partidos_empatados_equipo_partidos_ganados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='ruta_escudo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
