# Generated by Django 5.1.7 on 2025-03-27 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_simulador', '0007_userprofile_formacion'),
    ]

    operations = [
    ]
