# Generated by Django 5.1.7 on 2025-03-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_simulador', '0008_set_default_formacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='condicion_fisica',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='es_extranjero',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='habilidad_ataque',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='habilidad_defensa',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='salario',
        ),
    ]
